name: Jekyll site CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        ref: master
    - name: push
      uses: github-actions-x/commit@v2.0
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        push-branch: 'gh-pages'
        commit-message: 'publish'
        force-add: 'true'
